#!/bin/bash
# Script to apply all speed optimizations

echo "=== YOLO Speed Optimization ==="
echo ""
echo "1. Export YOLO models to ONNX (2-3x faster detection):"
echo ""
echo "# Camera A (yolov8s):"
echo "python3 detection/export_yolo_onnx.py --model yolov8s.pt --fp16"
echo ""
echo "# Cameras B/C (custom model):"
echo "python3 detection/export_yolo_onnx.py --model yolov8s_car_custom.pt --fp16"
echo ""
echo "Then update config to use .onnx files instead of .pt"
echo ""
echo "=== ONNX Runtime GPU Fix ==="
echo ""
echo "Current: ONNX running on CPU (slower)"
echo "Fix for CUDA 11.x:"
echo "  pip uninstall onnxruntime-gpu"
echo "  pip install onnxruntime-gpu==1.16.3"
echo ""
echo "=== Additional Optimizations ==="
echo ""
echo "1. Lower detection resolution (faster but less accurate):"
echo "   - Edit YOLO export: --imgsz 416  (default: 640)"
echo ""
echo "2. Process fewer frames:"
echo "   - Add frame skipping in video loop"
echo ""
echo "3. Reduce batch size if OOM:"
echo "   - REID_BATCHSIZE: 16  (current: 32)"
echo ""
echo "4. Use lighter YOLO model:"
echo "   - yolov8n instead of yolov8s (faster but less accurate)"
echo ""
echo "=== Current Setup ==="
echo "✓ EfficientNet-B0 (fine-tuned)"
echo "✓ ONNX ReID (CPU - needs GPU fix)"
echo "✓ FP16 enabled"
echo "✓ Batch size 32"
echo "✓ ByteTrack IOU tracker"
echo "✓ No attributes"
echo ""
echo "Expected speedup after YOLO ONNX + GPU ONNX: 5-10x additional"
